#!/usr/bin/env python3
"""
Generate the nvdsanalytics config from `configs/analytics/zones.yml`, and render previews so the
polygons can be checked against the actual footage instead of guessed.

    python3 scripts/make_zones.py --generate            # -> configs/analytics/analytics.txt
    python3 scripts/make_zones.py --preview 1 2 3       # -> build/zone_preview/camNN.jpg
    python3 scripts/make_zones.py --preview-all

## Why a generator instead of hand-written config

`nvdsanalytics` wants ABSOLUTE pixel coordinates, one flat INI with a section per stream
(`[roi-filtering-stream-0]`, `[roi-filtering-stream-1]`, …) — not one file per camera as the
Phase 2 plan sketched. Hand-maintaining that for 20 streams is miserable and silently
position-dependent: the section suffix is the SOURCE INDEX, so inserting a camera renumbers
everything after it.

`zones.yml` instead holds NORMALISED coordinates (0..1) keyed by camera number, which:

  * survives a resolution change (the demo is 1080p, the cameras may not be),
  * lets one zone definition be reused across cameras that share a source view — the 20 demo
    clips come from only 16 distinct views, and cam17-20 repeat cam01-04 with a time offset,
  * and keeps the product-level meaning (`severity`, which zones matter) next to the geometry,
    where a human editing it can see both.

## The preview is the point

Zone coordinates guessed from a description are almost always wrong, and wrong zones fail
silently — the pipeline runs, nothing is ever in the ROI, and the feature looks "not working"
rather than "mis-drawn". Rendering the polygon onto a real frame turns that into a visual check
that takes seconds.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
ZONES_YML = ROOT / "configs/analytics/zones.yml"
OUT_CFG = ROOT / "configs/analytics/analytics.txt"
PREVIEW_DIR = ROOT / "build/zone_preview"

# Colour per zone kind, RGB. Matches what the OSD will imply: red = restricted, amber =
# overcrowding-watched, green = ordinary walkway.
KIND_COLOR = {
    "roi": (60, 200, 90),
    "restricted": (235, 60, 50),
    "overcrowding": (245, 170, 40),
    "line": (80, 160, 255),
}


def load() -> dict:
    return yaml.safe_load(ZONES_YML.read_text())


def resolve_camera(cfg: dict, cam: int) -> dict | None:
    """Zones for camera `cam`, following a `same_as` alias if present.

    cam17..cam20 are the same source views as cam01..cam04 (different start offset), so they
    alias rather than duplicating coordinates that would then drift apart under editing.
    """
    cams = cfg.get("cameras") or {}
    entry = cams.get(cam)
    if entry is None:
        return None
    seen = {cam}
    while isinstance(entry, dict) and "same_as" in entry:
        ref = int(entry["same_as"])
        if ref in seen:
            raise SystemExit(f"same_as cycle at camera {cam}")
        seen.add(ref)
        entry = cams.get(ref)
        if entry is None:
            raise SystemExit(f"camera {cam} aliases missing camera {ref}")
    return entry


def px(points, w: int, h: int) -> list[tuple[int, int]]:
    return [(int(round(x * w)), int(round(y * h))) for x, y in points]


def fmt(points) -> str:
    return ";".join(f"{x};{y}" for x, y in points)


def generate(cfg: dict, streams: int) -> str:
    w = int(cfg.get("config_width", 1920))
    h = int(cfg.get("config_height", 1080))
    out: list[str] = [
        "# GENERATED by scripts/make_zones.py from configs/analytics/zones.yml — do not edit.",
        "# Section suffixes are SOURCE INDEX (0-based), i.e. -stream-0 is cam01.",
        "",
        "[property]",
        "enable=1",
        # These declare the coordinate space the values below are in. nvdsanalytics rescales to
        # the actual stream resolution, so the config stays valid if the cameras change size.
        f"config-width={w}",
        f"config-height={h}",
        # 0=off, 1=draw the zones, 2=draw zones plus per-zone text. 1 keeps a 20-tile wall
        # readable — at ~480x270 per tile, mode 2's text is unreadable overlap.
        f"osd-mode={cfg.get('osd_mode', 1)}",
        f"display-font-size={cfg.get('display_font_size', 10)}",
        "",
    ]

    for cam in range(1, streams + 1):
        entry = resolve_camera(cfg, cam)
        if not entry:
            continue
        idx = cam - 1                     # nvdsanalytics keys on 0-based source index
        zones = entry.get("zones") or []

        rois = [z for z in zones if z.get("kind", "roi") in ("roi", "restricted")]
        ocs = [z for z in zones if z.get("kind") == "overcrowding"]
        lines = [z for z in zones if z.get("kind") == "line"]

        if rois:
            out += [f"[roi-filtering-stream-{idx}]", "enable=1",
                    # inverse-roi=0 means "inside the polygon counts". class-id=-1 applies to
                    # every class; the compliance logic filters to people itself.
                    "inverse-roi=0", "class-id=-1"]
            for z in rois:
                out.append(f"roi-{z['name']}={fmt(px(z['points'], w, h))}")
            out.append("")

        if ocs:
            # ONE section per stream, not per zone: INI section names must be unique, so emitting
            # `[overcrowding-stream-0]` twice would silently drop the first. Multiple zones can
            # live in one section as separate `roi-` keys, but `object-threshold` is a section
            # property and therefore SHARED — differing thresholds cannot be expressed and are
            # reported rather than quietly ignored.
            thresholds = {int(z.get("threshold", 4)) for z in ocs}
            if len(thresholds) > 1:
                print(f"WARNING cam{cam:02d}: overcrowding zones declare different thresholds "
                      f"{sorted(thresholds)}; nvdsanalytics allows one per stream, using "
                      f"{min(thresholds)}")
            out += [f"[overcrowding-stream-{idx}]", "enable=1", "class-id=-1",
                    f"object-threshold={min(thresholds)}"]
            for z in ocs:
                out.append(f"roi-{z['name']}={fmt(px(z['points'], w, h))}")
            out.append("")

        if lines:
            out += [f"[line-crossing-stream-{idx}]", "enable=1", "class-id=-1",
                    # extended=0 keeps the crossing test to the drawn segment rather than the
                    # infinite line, which is what you want for a doorway.
                    "extended=0",
                    # loose: count the crossing even if the object was not detected in every
                    # intermediate frame. At 15fps analytics with track churn, 'strict' misses
                    # most real crossings.
                    "mode=loose"]
            for z in lines:
                # Four points: the first pair is the DIRECTION vector, the second pair is the
                # line being crossed. Getting these the wrong way round silently counts
                # crossings in the wrong direction.
                out.append(f"line-crossing-{z['name']}={fmt(px(z['points'], w, h))}")
            out.append("")

    return "\n".join(out) + "\n"


def severity_map(cfg: dict, streams: int) -> dict:
    """{camera_id: {zone_name: severity}} — product meaning, not consumed by nvdsanalytics."""
    out: dict[int, dict[str, str]] = {}
    for cam in range(1, streams + 1):
        entry = resolve_camera(cfg, cam)
        if not entry:
            continue
        out[cam] = {z["name"]: z.get("severity", "medium")
                    for z in (entry.get("zones") or []) if z.get("kind") != "line"}
    return out


def preview(cfg: dict, cams: list[int]) -> None:
    from PIL import Image, ImageDraw

    PREVIEW_DIR.mkdir(parents=True, exist_ok=True)
    for cam in cams:
        entry = resolve_camera(cfg, cam)
        if not entry:
            print(f"cam{cam:02d}: no zones defined, skipping")
            continue
        clip = ROOT / f"media/cam{cam:02d}.mp4"
        if not clip.exists():
            print(f"cam{cam:02d}: {clip} missing")
            continue
        frame = PREVIEW_DIR / f"cam{cam:02d}_raw.jpg"
        subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-ss",
                        str(cfg.get("preview_seek", 12)), "-i", str(clip),
                        "-frames:v", "1", str(frame)], check=True)

        img = Image.open(frame).convert("RGB")
        w, h = img.size
        d = ImageDraw.Draw(img, "RGBA")
        for z in entry.get("zones") or []:
            kind = z.get("kind", "roi")
            colour = KIND_COLOR.get(kind, (200, 200, 200))
            pts = px(z["points"], w, h)
            if kind == "line":
                # First pair = direction, second pair = the crossing line itself.
                d.line([pts[0], pts[1]], fill=colour + (255,), width=4)
                d.line([pts[2], pts[3]], fill=(255, 255, 255, 255), width=5)
                d.text((pts[2][0] + 6, pts[2][1] + 6), z["name"], fill=colour + (255,))
            else:
                d.polygon(pts, fill=colour + (60,), outline=colour + (255,))
                # Redraw the outline thickly — polygon()'s outline is 1px and invisible at 1080p.
                d.line(pts + [pts[0]], fill=colour + (255,), width=4)
                cx = sum(p[0] for p in pts) // len(pts)
                cy = sum(p[1] for p in pts) // len(pts)
                d.text((cx - 40, cy), f"{z['name']}\n({kind})", fill=(255, 255, 255, 255))
        out = PREVIEW_DIR / f"cam{cam:02d}.jpg"
        img.save(out, quality=88)
        print(f"cam{cam:02d}: {out}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--generate", action="store_true")
    ap.add_argument("--preview", nargs="*", type=int)
    ap.add_argument("--preview-all", action="store_true")
    ap.add_argument("--streams", type=int, default=20)
    args = ap.parse_args()

    cfg = load()
    if args.generate:
        OUT_CFG.parent.mkdir(parents=True, exist_ok=True)
        OUT_CFG.write_text(generate(cfg, args.streams))
        defined = [c for c in range(1, args.streams + 1) if resolve_camera(cfg, c)]
        print(f"wrote {OUT_CFG}  ({len(defined)}/{args.streams} cameras have zones)")
        missing = [c for c in range(1, args.streams + 1) if not resolve_camera(cfg, c)]
        if missing:
            # Loud on purpose: a camera with no zones silently reports zone=None for every
            # event, which reads as "zones are broken" rather than "zones are undefined".
            print(f"NO ZONES for cameras: {missing}")
    if args.preview_all:
        preview(cfg, [c for c in range(1, args.streams + 1) if resolve_camera(cfg, c)])
    elif args.preview:
        preview(cfg, args.preview)
    if not (args.generate or args.preview or args.preview_all):
        ap.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
