#!/usr/bin/env bash
# Runs on a SEPARATE machine from the Jetson — a laptop or any spare box on the same LAN.
# macOS and Linux, Intel or ARM.
#
# Stands up an RTSP camera farm here so the Jetson only has to do what a production box does:
# pull N streams off the network and decode them. Running the restreamers on the Jetson itself
# would burn CPU on the same silicon that is running inference, inflating the measured load and
# misrepresenting the production topology — real cameras are separate devices.
#
#   ./scripts/serve_rtsp_sources.sh start [count]
#   ./scripts/serve_rtsp_sources.sh stop
#   ./scripts/serve_rtsp_sources.sh status
#
# It prints the exact `rtsp_base:` line to paste into configs/demo.yml on the Jetson, then:
#   ./scripts/run_demo.sh 20 rtsp
#
# If you have real IP cameras, you do not need this at all — point sources.rtsp_base straight
# at them.
set -uo pipefail
cd "$(dirname "$0")/.."

PORT="${RTSP_PORT:-8554}"
MEDIAMTX_VER="v1.20.0"
BIN=build/bin/mediamtx
CONF=build/mediamtx-sources.yml
PIDS=build/rtsp_sources_pids
MEDIA_DIR="${MEDIA_DIR:-media}"

# LAN address of this machine, so the Jetson is told where to connect. macOS has no `hostname -I`
# and Linux has no `ipconfig`, so try both rather than assuming a platform.
lan_ip() {
  ipconfig getifaddr en0 2>/dev/null && return 0
  ipconfig getifaddr en1 2>/dev/null && return 0
  hostname -I 2>/dev/null | awk '{print $1}' | grep . && return 0
  ip -4 route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}' | grep . && return 0
  return 1
}

ensure_mediamtx() {
  [ -x "$BIN" ] && return
  mkdir -p build/bin
  local os arch tarball
  case "$(uname -s)" in
    Darwin) os=darwin ;;
    Linux)  os=linux ;;
    *) echo "ERROR: unsupported OS $(uname -s)"; exit 1 ;;
  esac
  case "$(uname -m)" in
    arm64|aarch64) arch=arm64 ;;
    x86_64|amd64)  arch=amd64 ;;
    *) echo "ERROR: unsupported arch $(uname -m)"; exit 1 ;;
  esac
  tarball="mediamtx_${MEDIAMTX_VER}_${os}_${arch}.tar.gz"
  echo "==> fetching $tarball"
  curl -fsSL "https://github.com/bluenviron/mediamtx/releases/download/${MEDIAMTX_VER}/${tarball}" \
    | tar xz -C build/bin mediamtx
}

start() {
  local count="${1:-20}" ip
  command -v ffmpeg >/dev/null || {
    echo "ERROR: ffmpeg not installed (macOS: brew install ffmpeg · Debian/Ubuntu: sudo apt install ffmpeg)"
    exit 1; }
  ensure_mediamtx
  stop >/dev/null 2>&1

  ip=$(lan_ip)
  [ -n "$ip" ] || { echo "ERROR: could not determine this machine's LAN IP"; exit 1; }

  cat > "$CONF" <<EOF
# Generated by scripts/serve_rtsp_sources.sh — do not edit by hand.
logLevel: warn
rtspAddress: :${PORT}
paths:
  all_others:
EOF

  echo "==> mediamtx on ${ip}:${PORT}"
  nohup "$BIN" "$CONF" > build/mediamtx-sources.log 2>&1 &
  echo $! > "$PIDS"
  sleep 2
  kill -0 "$(cat "$PIDS")" 2>/dev/null || {
    echo "ERROR: mediamtx failed to start:"; tail -5 build/mediamtx-sources.log; exit 1; }

  echo "==> publishing ${count} cameras from ${MEDIA_DIR}/"
  local started=0
  for i in $(seq 1 "$count"); do
    f=$(printf "%s/cam%02d.mp4" "$MEDIA_DIR" "$i")
    if [ ! -f "$f" ]; then
      echo "   !! $f missing — stopping at ${started} camera(s)"; break
    fi
    # -re paces at real time so it behaves like a 30fps camera rather than a firehose.
    # -c copy keeps the existing H.265 elementary stream: no re-encode, so this machine can
    # comfortably push 20 streams without becoming the bottleneck.
    #
    # -fflags +genpts is NOT optional, and it is not a codec detail. `-stream_loop -1` restarts
    # the file's timestamps at every loop, and the resulting discontinuity reaches the Jetson as
    # a glitched frame — DeepStream says so out loud ("Invalid PTS found in stream"). A smeared
    # block of warm pixels is exactly what a fire/smoke detector is looking for, so a real
    # camera farm that loops a 40s clip invents fire on innocent cameras every 40 seconds.
    #
    # Measured on cam14/cam16, same footage, three ways:
    #   file mode                          0 fire/smoke detections
    #   RTSP, no loop boundary             0
    #   RTSP, -stream_loop, no genpts      4 false fire incidents in 12 min, 27 PTS warnings
    #   RTSP, -stream_loop, WITH genpts    0, and 0 PTS warnings
    #
    # The same discontinuity also inflated smart-record clips from the requested 12s to 38-40s.
    # Regenerating timestamps at the loop point costs nothing and removes both.
    nohup ffmpeg -hide_banner -loglevel error -fflags +genpts -stream_loop -1 -re -i "$f" \
      -an -c:v copy -f rtsp -rtsp_transport tcp \
      "rtsp://127.0.0.1:${PORT}/$(printf 'cam%02d' "$i")" >/dev/null 2>&1 &
    echo $! >> "$PIDS"
    started=$((started + 1))
  done

  sleep 3
  echo
  status
  echo
  echo "  Sources now at : rtsp://${ip}:${PORT}/cam01 .. $(printf 'cam%02d' "$started")"
  echo
  echo "  Point the Jetson at this machine — in configs/demo.yml:"
  echo "      sources:"
  echo "        rtsp_base: rtsp://${ip}:${PORT}"
  echo "  then on the Jetson:  ./scripts/run_demo.sh ${started} rtsp"
}

stop() {
  if [ -f "$PIDS" ]; then
    while read -r pid; do kill "$pid" 2>/dev/null; done < "$PIDS"
    rm -f "$PIDS"
  fi
  pkill -f "ffmpeg.*rtsp://127.0.0.1:${PORT}" 2>/dev/null
  pkill -f "$(basename "$BIN") .*mediamtx-sources.yml" 2>/dev/null
  echo "==> stopped"
}

status() {
  local mtx rest
  mtx=$(pgrep -f "mediamtx-sources.yml" 2>/dev/null | wc -l | tr -d ' ')
  rest=$(pgrep -f "ffmpeg.*rtsp://127.0.0.1:${PORT}" 2>/dev/null | wc -l | tr -d ' ')
  echo "  mediamtx     : $([ "$mtx" -gt 0 ] && echo running || echo stopped)"
  echo "  restreamers  : ${rest}"
}

case "${1:-start}" in
  start)  start "${2:-}" ;;
  stop)   stop ;;
  status) status ;;
  *) echo "usage: $0 {start [count]|stop|status}"; exit 1 ;;
esac
