#!/usr/bin/env bash
# Runs on a SEPARATE machine from the Jetson — a laptop or any spare box on the same LAN.
# macOS and Linux, Intel or ARM.
#
# Stands up an RTSP camera farm here so the Jetson only has to do what a production box does:
# pull N streams off the network and decode them. Running the restreamers on the Jetson itself
# would burn CPU on the same silicon that is running inference, inflating the measured load and
# misrepresenting the production topology — real cameras are separate devices.
#
#   ./scripts/serve_rtsp_sources.sh start [count]
#   ./scripts/serve_rtsp_sources.sh stop
#   ./scripts/serve_rtsp_sources.sh status
#
# It prints the exact `rtsp_base:` line to paste into configs/demo.yml on the Jetson, then:
#   ./scripts/run_demo.sh 20 rtsp
#
# If you have real IP cameras, you do not need this at all — point sources.rtsp_base straight
# at them.
set -uo pipefail
cd "$(dirname "$0")/.."

PORT="${RTSP_PORT:-8554}"
# Interface to publish on. Empty means all of them, which is the point when the Jetson is a
# different machine. Set to 127.0.0.1 when this runs on the same box as the pipeline — otherwise a
# cloud instance is serving twenty camera streams to the open internet.
BIND="${RTSP_BIND:-}"
MEDIAMTX_VER="v1.20.0"
BIN=build/bin/mediamtx
CONF=build/mediamtx-sources.yml
PIDS=build/rtsp_sources_pids
MEDIA_DIR="${MEDIA_DIR:-media}"

# LAN address of this machine, so the Jetson is told where to connect. macOS has no `hostname -I`
# and Linux has no `ipconfig`, so try both rather than assuming a platform.
lan_ip() {
  ipconfig getifaddr en0 2>/dev/null && return 0
  ipconfig getifaddr en1 2>/dev/null && return 0
  hostname -I 2>/dev/null | awk '{print $1}' | grep . && return 0
  ip -4 route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}' | grep . && return 0
  return 1
}

ensure_mediamtx() {
  [ -x "$BIN" ] && return
  mkdir -p build/bin
  local os arch tarball
  case "$(uname -s)" in
    Darwin) os=darwin ;;
    Linux)  os=linux ;;
    *) echo "ERROR: unsupported OS $(uname -s)"; exit 1 ;;
  esac
  case "$(uname -m)" in
    arm64|aarch64) arch=arm64 ;;
    x86_64|amd64)  arch=amd64 ;;
    *) echo "ERROR: unsupported arch $(uname -m)"; exit 1 ;;
  esac
  tarball="mediamtx_${MEDIAMTX_VER}_${os}_${arch}.tar.gz"
  echo "==> fetching $tarball"
  curl -fsSL "https://github.com/bluenviron/mediamtx/releases/download/${MEDIAMTX_VER}/${tarball}" \
    | tar xz -C build/bin mediamtx
}

start() {
  local count="${1:-20}" ip
  command -v ffmpeg >/dev/null || {
    echo "ERROR: ffmpeg not installed (macOS: brew install ffmpeg · Debian/Ubuntu: sudo apt install ffmpeg)"
    exit 1; }
  ensure_mediamtx
  stop >/dev/null 2>&1

  ip=$(lan_ip)
  [ -n "$ip" ] || { echo "ERROR: could not determine this machine's LAN IP"; exit 1; }

  # This serves RTSP and nothing else, but mediamtx starts every protocol it supports by default:
  # RTP/RTCP on UDP 8000/8001, RTMP on 1935, HLS on 8888, WebRTC on 8889, SRT on 8890. Setting
  # only `rtspAddress` leaves all of those bound, so a second instance on the same host dies with
  # "listen tcp :1935: bind: address already in use" — naming a port that appears in no config
  # file and that neither instance was asked for. Running beside the demo's own mediamtx
  # (scripts/serve_rtsp.sh) is the normal case on a single-box rig, so each is turned off by name
  # and the two that remain are derived from PORT.
  #
  # `moq: no` is the same story one version later — v1.20 added a Media-over-QUIC listener on
  # 8892, and it is also what writes the auto.crt/auto.key pair into the working directory that
  # .gitignore exists to catch. Turning it off here means this instance never generates them.
  cat > "$CONF" <<EOF
# Generated by scripts/serve_rtsp_sources.sh — do not edit by hand.
logLevel: warn
rtspAddress: ${BIND}:${PORT}
rtpAddress: :$((PORT + 100))
rtcpAddress: :$((PORT + 101))
rtmp: no
hls: no
webrtc: no
srt: no
moq: no
api: no
metrics: no
pprof: no
playback: no
paths:
  all_others:
EOF

  echo "==> mediamtx on ${ip}:${PORT}"
  nohup "$BIN" "$CONF" > build/mediamtx-sources.log 2>&1 &
  echo $! > "$PIDS"
  sleep 2
  kill -0 "$(cat "$PIDS")" 2>/dev/null || {
    echo "ERROR: mediamtx failed to start:"; tail -5 build/mediamtx-sources.log; exit 1; }

  echo "==> publishing ${count} cameras from ${MEDIA_DIR}/"
  local started=0
  for i in $(seq 1 "$count"); do
    f=$(printf "%s/cam%02d.mp4" "$MEDIA_DIR" "$i")
    if [ ! -f "$f" ]; then
      echo "   !! $f missing — stopping at ${started} camera(s)"; break
    fi
    # -re paces at real time so it behaves like a 30fps camera rather than a firehose.
    # -c copy keeps the existing H.265 elementary stream: no re-encode, so this machine can
    # comfortably push 20 streams without becoming the bottleneck.
    #
    # A NOTE ON LOOPING, because it produces two symptoms that look like product bugs:
    #
    #   * occasional fire/smoke detections on cameras with no fire in them, and
    #   * smart-record clips longer than the duration that was requested.
    #
    # Both come from republishing a COMPRESSED stream in a loop. `-c copy` restarts the GOP
    # without re-sending parameter sets, so the Jetson's decoder loses reference frames — visible
    # as "Could not find ref with POC", "Error constructing the frame RPS" on the receiving end.
    # A smeared block of warm pixels is exactly what a fire detector is built to notice.
    #
    # The media itself is fine: decoding media/camNN.mp4 straight from disk gives ZERO errors,
    # and file-mode pipeline runs over the same footage detect no fire at all. Real cameras
    # encode natively for RTSP and do not restart a GOP mid-session, so none of this reaches a
    # production install — which is why the fix belongs here and not in a detector threshold.
    #
    # `-fflags +genpts` was tried and REVERTED. It does silence the "Invalid PTS" warnings, but
    # measured delivery over 12s: 317 frames plain vs 216 with genpts. Paying 30% of the frame
    # rate to partly mask a rig artifact that the VLM already rejects downstream is the wrong
    # trade — the pipeline dropped from ~300 fps to ~190 against a 300 fps realtime target.
    nohup ffmpeg -hide_banner -loglevel error -stream_loop -1 -re -i "$f" \
      -an -c:v copy -f rtsp -rtsp_transport tcp \
      "rtsp://127.0.0.1:${PORT}/$(printf 'cam%02d' "$i")" >/dev/null 2>&1 &
    echo $! >> "$PIDS"
    started=$((started + 1))
  done

  sleep 3
  echo
  status
  echo
  echo "  Sources now at : rtsp://${ip}:${PORT}/cam01 .. $(printf 'cam%02d' "$started")"
  echo
  echo "  Point the Jetson at this machine — in configs/demo.yml:"
  echo "      sources:"
  echo "        rtsp_base: rtsp://${ip}:${PORT}"
  echo "  then on the Jetson:  ./scripts/run_demo.sh ${started} rtsp"
}

stop() {
  if [ -f "$PIDS" ]; then
    while read -r pid; do kill "$pid" 2>/dev/null; done < "$PIDS"
    rm -f "$PIDS"
  fi
  pkill -f "ffmpeg.*rtsp://127.0.0.1:${PORT}" 2>/dev/null
  pkill -f "$(basename "$BIN") .*mediamtx-sources.yml" 2>/dev/null
  echo "==> stopped"
}

status() {
  local mtx rest
  mtx=$(pgrep -f "mediamtx-sources.yml" 2>/dev/null | wc -l | tr -d ' ')
  rest=$(pgrep -f "ffmpeg.*rtsp://127.0.0.1:${PORT}" 2>/dev/null | wc -l | tr -d ' ')
  echo "  mediamtx     : $([ "$mtx" -gt 0 ] && echo running || echo stopped)"
  echo "  restreamers  : ${rest}"
}

case "${1:-start}" in
  start)  start "${2:-}" ;;
  stop)   stop ;;
  status) status ;;
  *) echo "usage: $0 {start [count]|stop|status}"; exit 1 ;;
esac
